stages:
  - test
  - publish

variables:
  DOCKER_TLS_CERTDIR: ""
  IMAGE_REPO: registry.gitlab.eox.at/vs/stacture/statelix

default:
  image: quay.io/containers/podman:v4.6.2
  before_script:
    - cd statelix
    - podman login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - podman pull "$IMAGE_REPO":latest || true

test:
  stage: test
  tags:
    - podman
  script:
    - podman build --cache-from "$IMAGE_REPO" --cache-to "$IMAGE_REPO" -t "test-image" .
    - podman run "test-image" python3 -m pytest -p no:cacheprovider
    - podman run "test-image" ruff check --no-cache .
    - podman run "test-image" mypy .

publish-branch:
  stage: publish
  tags:
    - podman
  script:
    - podman build --cache-from "$IMAGE_REPO" --cache-to "$IMAGE_REPO" -t "$IMAGE_REPO:${CI_COMMIT_BRANCH}" -t "$IMAGE_REPO:${CI_COMMIT_SHA}" .
    - podman push "$IMAGE_REPO:${CI_COMMIT_BRANCH}" # this can lead to race conditions of pipelines and does not maintain commit time order
    - podman push "$IMAGE_REPO:${CI_COMMIT_SHA}"
  except:
    - tags
    - main

publish:
  stage: publish
  tags:
    - podman
  script:
    - podman build --cache-from "$IMAGE_REPO" --cache-to "$IMAGE_REPO" -t "$IMAGE_REPO:${CI_COMMIT_TAG}" -t "$IMAGE_REPO:${CI_COMMIT_SHA}" .
    - podman push "$IMAGE_REPO:${CI_COMMIT_TAG}"
    - podman push "$IMAGE_REPO:${CI_COMMIT_SHA}"
  only:
    - tags

publish-main:
  stage: publish
  tags:
    - podman
  script:
    - SORTABLE_VERSION=main-$(date +%s)-$CI_COMMIT_SHORT_SHA
    - podman build --cache-from "$IMAGE_REPO" --cache-to "$IMAGE_REPO" -t "$IMAGE_REPO":latest -t "$IMAGE_REPO:${CI_COMMIT_SHA}" -t "$IMAGE_REPO:${SORTABLE_VERSION}" .
    - podman push "$IMAGE_REPO":latest
    - podman push "$IMAGE_REPO:${CI_COMMIT_SHA}"
    - podman push "$IMAGE_REPO:${SORTABLE_VERSION}"

  only:
    - main
